### ISSUE TITLE
"Address already in use" error

### ISSUE THREAD

**Issue by NotNorthKorea** [AFLplusplus/LibAFL#147]
Hello friends,

I'm having an issue with the llmp connection code. I couldn't get any of the non-launcher example fuzzers to work due to the same error:

```
$ target/release/libfuzzer_stb_image
Workdir: "/home/user/fuzz/LibAFL/fuzzers/libfuzzer_stb_image"
Doing broker things. Run this tool again to start fuzzing in a client.
```

```
$ target/release/libfuzzer_stb_image
Workdir: "/home/user/fuzz/LibAFL/fuzzers/libfuzzer_stb_image"
thread 'main' panicked at 'Failed to setup the restarter: File IO failed: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/main.rs:62:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The in process launcher was also not very reliable on some of the examples. I ran cargo test:

```
running 17 tests
test bolts::rands::tests::test_rands ... ok
test bolts::rands::tests::test_random_seed ... ok
test executors::inprocess::tests::test_inmem_exec ... ok
test events::tests::test_event_serde ... ok
test executors::test::nop_executor ... ok
test inputs::bytes::tests::test_input ... ok
test mutators::scheduled::tests::test_mut_scheduled ... ok
test corpus::queue::tests::test_queuecorpus ... ok
test observers::tests::test_observer_serde ... ok
test mutators::token_mutations::tests::test_read_tokens ... ok
test mutators::scheduled::tests::test_havoc ... ok
test executors::forkserver::tests::test_forkserver ... ok
test bolts::compress::tests::test_threshold ... ok
test bolts::compress::tests::test_compression ... ok
test bolts::llmp::tests::llmp_connection ... FAILED
test mutators::mutations::tests::test_mutators ... ok
test tests::test_fuzzer ... ok

failures:

---- bolts::llmp::tests::llmp_connection stdout ----
We're the client (internal port already bound by broker, Os {
    code: 98,
    kind: AddrInUse,
    message: "Address already in use",
})
Connected to port 1337
thread 'bolts::llmp::tests::llmp_connection' panicked at 'Could not bind to port as broker', libafl/src/bolts/llmp.rs:2551:39
stack backtrace:
   0: std::panicking::begin_panic
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: libafl::bolts::llmp::tests::llmp_connection
             at ./src/bolts/llmp.rs:2551:39
   2: libafl::bolts::llmp::tests::llmp_connection::{{closure}}
             at ./src/bolts/llmp.rs:2548:5
   3: core::ops::function::FnOnce::call_once
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    bolts::llmp::tests::llmp_connection

test result: FAILED. 16 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.63s
```

```
$ uname -a
Linux desktop1 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23
```

**Comment by domenukk** [comment]
The output in the first two boxes looks good, the "Error" is just a debug output, it means you have an actual LLMP Client/ fuzzer.

The testcases, however, should work. Is there any way you're actually running something on 1337? Else the port may still be blocked?

**Comment by NotNorthKorea** [comment]
Ah the `cargo test` error was actually my bad as I still had a fuzzer instance running.

But the other non-errors are still an issue e.g. `libfuzzer_stb_image` and others. They don't start, there is no other error messages, etc. And sometimes the other launcher ones are flakey, for example I had one working on my laptop and transferred it to a digital ocean instance and it would be either not receiving any connections or sometimes just 1 (if I was using `--cores 2` or more).

I just did a fresh `git clone`, `cd LibAFL/fuzzers/libfuzzer_stb_image`, `cargo build --release`, and ran the resulting bin in two terminals and it's the same -> the client doesn't connect.

**Comment by tokatoka** [comment]
I can get the same error Message as NotNorthKorea has reported.
Fuzzers works good well before this commit a0804fd24d83801361ce014412ce821a427b2119

**Comment by s1341** [comment]
Note that `--cores 2` does not means '2 cores'. It means run on core number 2. Getting one connection is correct behavior.

**Comment by andreafioraldi** [comment]
Shoule be solved, please test

**Comment by NotNorthKorea** [comment]
Works great, thanks <3
