### ISSUE TITLE
qemu_coverage build error

### ISSUE THREAD

**Issue by Nicholas-wei** [AFLplusplus/LibAFL#1858]
**Describe the bug**
When running `cargo make run` under ./fuzzers/qemu_coverage, error occurs

**To Reproduce**
1. open ./fuzzers/qemu_coverage
2. run `cargo make run`

**Expected behavior**
I think a qemu-based fuzzer should be built without error

**Screen output/Screenshots**
$ cargo make run
[cargo-make] INFO - cargo make 0.37.9
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Project: qemu_coverage
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: run
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Skipping Task: target_dir 
[cargo-make] INFO - Skipping Task: arch_target_dir 
[cargo-make] INFO - Skipping Task: deps_dir 
[cargo-make] INFO - Skipping Task: zlib_unix_wget 
[cargo-make] INFO - Skipping Task: zlib 
[cargo-make] INFO - Skipping Task: libpng_unix_wget 
[cargo-make] INFO - Skipping Task: libpng 
[cargo-make] INFO - Running Task: harness
[cargo-make] INFO - Execute Command: "cargo" "build" "--profile" "release" "--features" "x86_64" "--target-dir" "\~/libafl_study/LibAFL/fuzzers/qemu_coverage/target/x86_64"
   Compiling libafl_qemu_sys v0.11.2 (\~/libafl_study/LibAFL/libafl_qemu/libafl_qemu_sys)
error: failed to run custom build command for `libafl_qemu_sys v0.11.2 (~/libafl_study/LibAFL/libafl_qemu/libafl_qemu_sys)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `~/libafl_study/LibAFL/fuzzers/qemu_coverage/target/x86_64/release/build/libafl_qemu_sys-13ed092abb252436/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=emulation_mode="usermode"
  cargo:rerun-if-env-changed=EMULATION_MODE
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=build_linux.rs
  cargo:rerun-if-env-changed=CPU_TARGET
  cargo:rustc-cfg=cpu_target="x86_64"
  cargo:rerun-if-env-changed=CUSTOM_QEMU_DIR
  cargo:rerun-if-env-changed=CUSTOM_QEMU_NO_BUILD
  cargo:rerun-if-env-changed=CUSTOM_QEMU_NO_CONFIGURE
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  ERROR: unknown option --as-shared-lib
  Try './configure --help' for more information

  --- stderr
  make: *** No targets specified and no makefile found.  Stop.
  thread 'main' panicked at ~/libafl_study/LibAFL/libafl_qemu/libafl_qemu_build/src/build.rs:359:14:
  Failed to read linkinfo.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0:     0x5569372569b6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:     0x5569372569b6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5569372569b6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
     3:     0x5569372569b6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x5569372820a0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
     5:     0x5569372820a0 - core::fmt::write::h3ed6aeaa977c8e45
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
     6:     0x556937253d7f - std::io::Write::write_fmt::h78b18af5775fedb5
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
     7:     0x556937256794 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x556937256794 - std::sys_common::backtrace::print::h85035a511aafe7a8
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x556937258077 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
    10:     0x556937257dd9 - std::panicking::default_hook::hf5fcb0f213fe709a
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
    11:     0x556937258508 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
    12:     0x5569372583e2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
    13:     0x556937256eb6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
    14:     0x556937258140 - rust_begin_unwind
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
    15:     0x556936af3af5 - core::panicking::panic_fmt::h784f20a50eaab275
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
    16:     0x556936af3fe3 - core::result::unwrap_failed::h03d8a5018196e1cd
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
    17:     0x556936af959a - core::result::Result<T,E>::expect::h1f36b3ac3d03cbcc
    18:     0x556936b08152 - libafl_qemu_build::build::build::he0dcc3cd2341c2e3
    19:     0x556936aff336 - libafl_qemu_build::build_with_bindings::hba17d3ce53d0f96d
    20:     0x556936af52b1 - build_script_build::host_specific::build::h39f3fa46fb0b435c
    21:     0x556936af4bb6 - build_script_build::main::h16c80cd93fd95569
    22:     0x556936af4723 - core::ops::function::FnOnce::call_once::h86a7e0bb3a499184
    23:     0x556936af43b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4f9bac03883fab22
    24:     0x556936af44e9 - std::rt::lang_start::{{closure}}::h52e22bc9ee0a8c74
    25:     0x55693724e861 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
    26:     0x55693724e861 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
    27:     0x55693724e861 - std::panicking::try::h8bbf75149211aaaa
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
    28:     0x55693724e861 - std::panic::catch_unwind::h8c78ec68ebea34cb
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
    29:     0x55693724e861 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
    30:     0x55693724e861 - std::panicking::try::do_call::hcb3194972c74716d
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
    31:     0x55693724e861 - std::panicking::try::hcdc6892c5f0dba4c
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
    32:     0x55693724e861 - std::panic::catch_unwind::h4910beb4573f4776
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
    33:     0x55693724e861 - std::rt::lang_start_internal::h6939038e2873596b
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
    34:     0x556936af44c7 - std::rt::lang_start::h113547ea04817ecb
    35:     0x556936af55b5 - main
    36:     0x7f8a9e89cd90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    37:     0x7f8a9e89ce40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    38:     0x556936af42e5 - _start
    39:                0x0 - <unknown>
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.

**Additional context**
I have install the `dependencies` in README.md under `qemu_coverage` dir
I have set the environment variable CUSTOM_QEMU_DIR to a qemu downloaded from github(qemu v4.2.1)
libafl version is  v0.11.2

**Comment by rmalmain** [comment]
Hello,

If I understood well, you downloaded an old vanilla version of QEMU on GitHub and set `CUSTOM_QEMU_DIR` to its directory. In that case, this kind of error is to be expected: `CUSTOM_QEMU_DIR` must point to a clone of [qemu-libafl-bridge](https://github.com/AFLplusplus/qemu-libafl-bridge) to work correctly.

**Comment by Nicholas-wei** [comment]
Thanks! This problem above is solved. However, there are still some problems when building `qemu_coverage`. I am using the `Dockerfile` in the root directory when building the environment
**description**
In the `readme` file , the suggested llvm version is below 17.0.0, which is suitable for rust 1.72(Since rust 1.73 is suitable with llvm-17.0.2, which is above 17.0.0). The following dependency gets wrong when executing `cargo make run` under `fuzzers/qemu_coverage`
```shell
`package `clap_lex v0.7.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0` 
```
However, if I use rustc 1.74, and llvm 17.0.4 which is compatible with rust 1.74 , there are still some problems
```shell
[cargo-make] INFO - Execute Command: "cargo" "build" "--profile" "release" "--features" "x86_64" "--target-dir" "/libafl_new/LibAFL/fuzzers/qemu_coverage/target/x86_64"
   Compiling libafl v0.11.2 (/libafl_new/LibAFL/libafl)
error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> /libafl_new/LibAFL/libafl/src/executors/differential.rs:208:41
    |
208 |         self.primary = OwnedMutPtr::Ptr(core::ptr::from_ref::<A>(primary) as *mut A);
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information

error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> /libafl_new/LibAFL/libafl/src/executors/differential.rs:209:43
    |
209 |         self.secondary = OwnedMutPtr::Ptr(core::ptr::from_ref::<B>(secondary) as *mut B);
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information
```

Are there any way to solve the problem?

**Comment by domenukk** [comment]
> Are there any way to solve the problem?

Is this with the latest cargo version? Does `rustup upgrade` help, by any chance?

**Comment by Nicholas-wei** [comment]
Thanks! After trying updating to the latest rustc version(1.76.0) with compatiable LLVM version(17.0.6) on ubuntu 22.04, `fuzzers/qemu-coverage` compiles successfully.
Maybe consider changing the following line in README?
```txt
LLVM tools
The LLVM tools (including clang, clang++) are needed (newer than LLVM 11.0.0 up to LLVM 17.0.0)  <---- LLVM version needs change
```
