### ISSUE TITLE
libafl_libfuzzer fails to build with error: 'sanitizer/allocator_interface.h' file not found

### ISSUE THREAD

**Issue by 0xalpharush** [AFLplusplus/LibAFL#2535]
I am trying to use the libafl_libfuzzer shim and hitting this error:
```
    --- stderr
    src/sanitizer_interfaces.h:1:10: fatal error: 'sanitizer/allocator_interface.h' file not found
    thread 'main' panicked at /root/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/2c676f0/libafl_targets/build.rs:237:14:
    Couldn't generate the sanitizer headers!: ClangDiagnostic("src/sanitizer_interfaces.h:1:10: fatal error: 'sanitizer/allocator_interface.h' file not found\n")
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  thread 'main' panicked at /root/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/2c676f0/libafl_libfuzzer/build.rs:137:5:
  Couldn't build runtime crate! Did you remember to use nightly? (`rustup default nightly` to install)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to build fuzz script: RUSTFLAGS="-Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Cllvm-args=-sanitizer-coverage-trace-compares --cfg fuzzing -Clink-dead-code -Cllvm-args=-sanitizer-coverage-stack-depth -Cdebug-assertions -C codegen-units=1" "cargo" "build" "--manifest-path" "/root/fuzz/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--config" "profile.release.debug=true" "--bin" "fuzz_target1"

```

As I have not been able to find any info on this error elsewhere, I'd appreciate any help. I am using `rustc 1.83.0-nightly (c52c23b6f 2024-09-16)` and running on an X86_64 Ubuntu server

**Comment by 0xalpharush** [comment]
https://github.com/AFLplusplus/LibAFL/blob/2c676f0352ad81e741a8c506678b335247d58983/libafl_libfuzzer/build.rs#L137-L140

**Comment by addisoncrump** [comment]
Looks like you're OOMing during build. Check your memory usage during the build?

**Comment by 0xalpharush** [comment]
How much memory is expected to be required?
```
Command exited with non-zero status 1
        Command being timed: "cargo fuzz build"
        User time (seconds): 26.33
        System time (seconds): 0.71
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:27.07
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 838316
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 257070
        Voluntary context switches: 706
        Involuntary context switches: 602
        Swaps: 0
        File system inputs: 2536
        File system outputs: 48
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```

**Comment by addisoncrump** [comment]
LTO is pretty greedy... unfortunately we don't have a good way to disable this. At build time I observed 2GB, at link time I observed up to 4.2GB.
