### ISSUE TITLE
Suspicios graph on FuzzBench problably related to the crash restart

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#336]
https://www.fuzzbench.com/reports/experimental/2021-10-22-libafl/index.html#sqlite3_ossfuzz-summary

**Comment by andreafioraldi** [comment]
@tokatoka it is fuzzbench or furrbench_gsoc? seems like an unregistered metadata in state.

**Comment by tokatoka** [comment]
This result is from fuzzbench_gsoc.

**Comment by tokatoka** [comment]
I can do the `fuzzbench` run also ;), (but maybe tomorrow)

**Comment by tokatoka** [comment]
The same error is triggered on fuzzbench too.
```
[/home/toka/LibAFL/libafl/src/events/simple.rs:344] "Spawning next client (id {})" = "Spawning next client (id {})"
[/home/toka/LibAFL/libafl/src/events/simple.rs:344] ctr = 2595
We're a client, let's fuzz :)
thread '<unnamed>' panicked at 'Cannot deserialize an unregistered type', /home/toka/LibAFL/libafl/src/bolts/serdeany.rs:591:1
stack backtrace:
   0:           0x6f250a - std::backtrace_rs::backtrace::libunwind::trace::hd3a6cb8e32f9fc43
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:           0x6f250a - std::backtrace_rs::backtrace::trace_unsynchronized::h6dcceebcd6a9f2ab
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x6f250a - std::sys_common::backtrace::_print_fmt::h4eacf4e9ad977499
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:           0x6f250a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e42c22572a7e7b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:           0x68a0cc - core::fmt::write::h072b578a8e90aa54
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:           0x6f1bf4 - std::io::Write::write_fmt::hc32d3cabefff1d24
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:           0x6f1a21 - std::sys_common::backtrace::_print::h058b85b6efc15780
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:           0x6f1a21 - std::sys_common::backtrace::print::hdb7de10b704104b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:           0x6f1a21 - std::panicking::default_hook::{{closure}}::h5451997d203bda2f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:           0x6f1a21 - std::panicking::default_hook::h419b121e68f746a2
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:227:9
  10:           0x6f1a21 - std::panicking::rust_panic_with_hook::h32c44b1364c1c247
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:           0x711a58 - std::panicking::begin_panic_handler::{{closure}}::he2e5f48fb16982d1
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
  12:           0x7119d6 - std::sys_common::backtrace::__rust_end_short_backtrace::haea54a33f9e18aba
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
  13:           0x711992 - rust_begin_unwind
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  14:           0x409910 - core::panicking::panic_fmt::h824e0febbdf5e655
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  15:           0x409bb2 - core::option::expect_failed::h3867f03951c5322d
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/option.rs:1615:5
  16:           0x619203 - core::option::Option<T>::expect::h6e2e23c1e2433281
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/option.rs:698:21
  17:           0x619203 - <libafl::bolts::serdeany::serdeany_registry::BoxDynVisitor as serde::de::Visitor>::visit_seq::h00dac5e0f6861242
                               at /home/toka/LibAFL/libafl/src/bolts/serdeany.rs:122:26
  18:           0x619203 - <&mut postcard::de::deserializer::Deserializer as serde::de::Deserializer>::deserialize_seq::h21b469465a218beb
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:347:9
  19:           0x619203 - libafl::bolts::serdeany::<impl serde::de::Deserialize for alloc::boxed::Box<dyn libafl::bolts::serdeany::SerdeAny>>::deserialize::h145846dbc8c26dcd
                               at /home/toka/LibAFL/libafl/src/bolts/serdeany.rs:585:17
  20:           0x619203 - <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::h70df7a38d705ce59
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  21:           0x619203 - <postcard::de::deserializer::MapAccess as serde::de::MapAccess>::next_value_seed::hc0ab91888fdda427
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:105:9
  22:           0x619203 - serde::de::MapAccess::next_entry_seed::h7a0de0fa67bf25a4
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1812:34
  23:           0x619203 - serde::de::MapAccess::next_entry::hec1033af789f757d
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1860:9
  24:           0x619203 - <hashbrown::external_trait_impls::serde::map::<impl serde::de::Deserialize for hashbrown::map::HashMap<K,V,S>>::deserialize::MapVisitor<K,V,S> as serde::de::Visitor>::visit_map::h46aee71c4caecb08
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/external_trait_impls/serde.rs:75:52
  25:           0x619203 - <&mut postcard::de::deserializer::Deserializer as serde::de::Deserializer>::deserialize_map::h53b8a79cd172738f
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:381:9
  26:           0x619203 - hashbrown::external_trait_impls::serde::map::<impl serde::de::Deserialize for hashbrown::map::HashMap<K,V,S>>::deserialize::ha17bb75f1b46f5ef
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/external_trait_impls/serde.rs:86:13
  27:           0x619203 - <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::hbcbae81e014c7db2
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  28:           0x619203 - <postcard::de::deserializer::SeqAccess as serde::de::SeqAccess>::next_element_seed::hb7ff11be4d5f4233
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:70:21
  29:           0x619203 - serde::de::SeqAccess::next_element::hf602cc658e1baa62
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1707:9
  30:           0x619203 - <libafl::bolts::serdeany::serdeany_registry::_::<impl serde::de::Deserialize for libafl::bolts::serdeany::serdeany_registry::SerdeAnyMap>::deserialize::__Visitor as serde::de::Visitor>::visit_seq::hdef95391be46aa8d
                               at /home/toka/LibAFL/libafl/src/bolts/serdeany.rs:591:1
  31:           0x619203 - <&mut postcard::de::deserializer::Deserializer as serde::de::Deserializer>::deserialize_tuple::h9d9b7331cbd3acef
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:357:9
  32:           0x619203 - <&mut postcard::de::deserializer::Deserializer as serde::de::Deserializer>::deserialize_struct::haf145aec2170365f
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:396:9
  33:           0x619203 - libafl::bolts::serdeany::serdeany_registry::_::<impl serde::de::Deserialize for libafl::bolts::serdeany::serdeany_registry::SerdeAnyMap>::deserialize::h5c24a66b27d45407
                               at /home/toka/LibAFL/libafl/src/bolts/serdeany.rs:188:33
  34:           0x619203 - <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::hefbb450d3f3d1250
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:785:9
  35:           0x619203 - <postcard::de::deserializer::SeqAccess as serde::de::SeqAccess>::next_element_seed::h92a4a5e0e9f5e12a
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:70:21
  36:           0x619203 - serde::de::SeqAccess::next_element::h8ee5e3b5a8bb1f79
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/de/mod.rs:1707:9
  37:           0x640399 - <libafl::state::_::<impl serde::de::Deserialize for libafl::state::StdState<C,FT,I,R,SC>>::deserialize::__Visitor<C,FT,I,R,SC> as serde::de::Visitor>::visit_seq::h23a3f16a45c6ab93
                               at /home/toka/LibAFL/libafl/src/state/mod.rs:140:21
  38:           0x640399 - <&mut postcard::de::deserializer::Deserializer as serde::de::Deserializer>::deserialize_tuple::h01974860066442f2
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:357:9
  39:           0x640399 - <&mut postcard::de::deserializer::Deserializer as serde::de::Deserializer>::deserialize_struct::hb63ae788adbe841f
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/deserializer.rs:396:9
  40:           0x640399 - libafl::state::_::<impl serde::de::Deserialize for libafl::state::StdState<C,FT,I,R,SC>>::deserialize::h831cb2916f69c053
                               at /home/toka/LibAFL/libafl/src/state/mod.rs:140:21
  41:           0x640399 - postcard::de::from_bytes::hdba828331189a349
                               at /home/toka/.cargo/registry/src/github.com-1ecc6299db9ec823/postcard-0.7.2/src/de/mod.rs:16:13
  42:           0x640399 - libafl::bolts::staterestore::StateRestorer<SP>::restore::h5a21e23c270c46fd
                               at /home/toka/LibAFL/libafl/src/bolts/staterestore.rs:233:28
  43:           0x640399 - libafl::events::simple::SimpleRestartingEventManager<C,I,S,SC,SP,ST>::launch::hda0db8cf0c49995c
                               at /home/toka/LibAFL/libafl/src/events/simple.rs:392:34
  44:           0x640399 - fuzzbench::fuzz::h94a023e84cf9bb0e
                               at /home/toka/LibAFL/fuzzers/fuzzbench/src/lib.rs:186:34
  45:           0x638efe - libafl_main
                               at /home/toka/LibAFL/fuzzers/fuzzbench/src/lib.rs:145:5
  46:           0x40ee6d - main
                               at /home/toka/LibAFL/libafl_targets/src/libfuzzer.c:22:3
  47:     0x7fc82b8990b3 - __libc_start_main
  48:           0x40eeae - _start
  49:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
[/home/toka/LibAFL/libafl/src/events/simple.rs:344] "Spawning next client (id {})" = "Spawning next client (id {})"
[/home/toka/LibAFL/libafl/src/events/simple.rs:344] ctr = 2596
We're a client, let's fuzz :)
^C
toka@toka-desktop:~/LibAFL/fuzzers/fuzzbench$ vim text
```

**Comment by tokatoka** [comment]
I have this in /tmp
```
toka@toka-desktop:~/LibAFL/fuzzers/fuzzbench$ ls /tmp | grep libafl
54e0c58e3cad848f.libafl_state
```
I can send you this tmpfile.

**Comment by domenukk** [comment]
Just saw this.
The deserializer doesn't complain about missing bytes but about an unknown type, which sounds more like something in serde/postcard?

**Comment by andreafioraldi** [comment]
can be a corpputed serialized state

**Comment by domenukk** [comment]
Maybe we can debug this by adding more verbose logging output here
https://github.com/AFLplusplus/LibAFL/blob/b4e15fe9f3764a783bb5911460c020b5facb4706/libafl/src/bolts/serdeany.rs#L127

**Comment by andreafioraldi** [comment]
this is now # 1 priority

**Comment by tokatoka** [comment]
just fyi:
you can also reproduce this easily by applying this patch and run `cargo test`
```
diff --git a/libafl/src/bolts/staterestore.rs b/libafl/src/bolts/staterestore.rs
index b006603..da257f1 100644
--- a/libafl/src/bolts/staterestore.rs
+++ b/libafl/src/bolts/staterestore.rs
@@ -215,10 +215,8 @@ where
         };
         let mut state = bytes;
         let mut file_content;
-        if state_shmem_content.buf_len == 0 {
-            return Ok(Option::None);
-        } else if state_shmem_content.is_disk {
-            let filename: String = postcard::from_bytes(bytes)?;
+
+            let filename: String = "f549332cba738b1c.libafl_state".to_string();
             let tmpfile = temp_dir().join(&filename);
             file_content = vec![];
             File::open(tmpfile)?.read_to_end(&mut file_content)?;
@@ -229,7 +227,6 @@ where
                 )));
             }
             state = &file_content;
-        }
         let deserialized = postcard::from_bytes(state)?;
         Ok(Some(deserialized))
     }
```
using the libafl_state uploaded on discord

**Comment by andreafioraldi** [comment]
> just fyi: you can also reproduce this easily by applying this patch and run `cargo test`
> 
> ```
> diff --git a/libafl/src/bolts/staterestore.rs b/libafl/src/bolts/staterestore.rs
> index b006603..da257f1 100644
> --- a/libafl/src/bolts/staterestore.rs
> +++ b/libafl/src/bolts/staterestore.rs
> @@ -215,10 +215,8 @@ where
>          };
>          let mut state = bytes;
>          let mut file_content;
> -        if state_shmem_content.buf_len == 0 {
> -            return Ok(Option::None);
> -        } else if state_shmem_content.is_disk {
> -            let filename: String = postcard::from_bytes(bytes)?;
> +
> +            let filename: String = "f549332cba738b1c.libafl_state".to_string();
>              let tmpfile = temp_dir().join(&filename);
>              file_content = vec![];
>              File::open(tmpfile)?.read_to_end(&mut file_content)?;
> @@ -229,7 +227,6 @@ where
>                  )));
>              }
>              state = &file_content;
> -        }
>          let deserialized = postcard::from_bytes(state)?;
>          Ok(Some(deserialized))
>      }
> ```
> 
> using the libafl_state uploaded on discord

Thanks, but I wanna reproduce it again after my memory fixes. Maybe it is related to the OOM.

**Comment by andreafioraldi** [comment]
```[/libafl/libafl/src/events/simple.rs:343] "Spawning next client (id {})" = "Spawning next client (id {})"
[/libafl/libafl/src/events/simple.rs:343] ctr = 2547
We're a client, let's fuzz :)
thread '<unnamed>' panicked at 'Cannot deserialize an unregistered type', /libafl/libafl/src/bolts/serdeany.rs:589:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[/libafl/libafl/src/events/simple.rs:343] "Spawning next client (id {})" = "Spawning next client (id {})"
[/libafl/libafl/src/events/simple.rs:343] ctr = 2548
We're a client, let's fuzz :)
thread '<unnamed>' panicked at 'Cannot deserialize an unregistered type', /libafl/libafl/src/bolts/serdeany.rs:589:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[/libafl/libafl/src/events/simple.rs:343] "Spawning next client (id {})" = "Spawning next client (id {})"
[/libafl/libafl/src/events/simple.rs:343] ctr = 2549
We're a client, let's fuzz :)
thread '<unnamed>' panicked at 'Cannot deserialize an unregistered type', /libafl/libafl/src/bolts/serdeany.rs:589:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[/libafl/libafl/src/events/simple.rs:343] "Spawning next client (id {})" = "Spawning next client (id {})"
[/libafl/libafl/src/events/simple.rs:343] ctr = 2550
We're a client, let's fuzz :)
thread '<unnamed>' panicked at 'Cannot deserialize an unregistered type', /libafl/libafl/src/bolts/serdeany.rs:589:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[/libafl/libafl/src/events/simple.rs:343] "Spawning next client (id {})" = "Spawning next client (id {})"
[/libafl/libafl/src/events/simple.rs:343] ctr = 2551
```

@domenukk the respawner should stop respaning after an error of the child...

**Comment by domenukk** [comment]
It usually does. It looks it there is an unconsumed state in the restorer page, and if so, restarts the child.

If the child died during restore, however, I guess it never consumed the state hence the restart...
Think it's fine to just fix the root cause here?

**Comment by andreafioraldi** [comment]
With CachedOnDiskCorpus after 6h it is still running, probably it is an OOM with OnDiskCorpus

**Comment by andreafioraldi** [comment]
```[Stats #0] clients: 1, corpus: 17882, objectives: 0, executions: 42921333, exec/sec: 2877
[Testcase #0] clients: 1, corpus: 17883, objectives: 0, executions: 42923466, exec/sec: 3428
[Stats #0] clients: 1, corpus: 17883, objectives: 0, executions: 42923466, exec/sec: 3457
[Testcase #0] clients: 1, corpus: 17884, objectives: 0, executions: 42936027, exec/sec: 3485
[Stats #0] clients: 1, corpus: 17884, objectives: 0, executions: 42947173, exec/sec: 4008
[Objective #0] clients: 1, corpus: 17884, objectives: 1, executions: 42947173, exec/sec: 4251
[/libafl/libafl/src/events/simple.rs:343] "Spawning next client (id {})" = "Spawning next client (id {})"
[/libafl/libafl/src/events/simple.rs:343] ctr = 1
We're a client, let's fuzz :)
Subsequent run. Loaded previous state.
Let's fuzz :)
[Stats #0] clients: 1, corpus: 17884, objectives: 1, executions: 0, exec/sec: 0
[Testcase #0] clients: 1, corpus: 17885, objectives: 1, executions: 42950639, exec/sec: 0
[Stats #0] clients: 1, corpus: 17885, objectives: 1, executions: 42966329, exec/sec: 2863376
[Stats #0] clients: 1, corpus: 17885, objectives: 1, executions: 42966329, exec/sec: 5230
[Testcase #0] clients: 1, corpus: 17886, objectives: 1, executions: 42977110, exec/sec: 5454
[Stats #0] clients: 1, corpus: 17886, objectives: 1, executions: 42981198, exec/sec: 5223
```

Yup, it restarted wel asfter the first crash

**Comment by tokatoka** [comment]
but on my first experiment with fuzzbench_gsoc it had 6 successful staterestores before.
and on the 7th staterestore, it crashed.

From my experience, time to expose this bug could vary.
On my first experiment it took 4h 48min as I stated.
I remember the second time I tried it with fuzzbench, it took less than 2 hours.
and on the third time, when I tried to send you a libafl_state dump, I remember it took around 5 hours....

but yes all of them are before the memory leak fix.

**Comment by domenukk** [comment]
There's a chance that saving the state doesn't work because it uses the same heap, and the heap got corrupted, I guess?
Or it OOMs while dumping the state to disk

**Comment by andreafioraldi** [comment]
It happened during the night, with woff2 too.

**Comment by andreafioraldi** [comment]
there is `fatal runtime error: failed to initiate panic, error 5` dunno what is, we must solve the restart @domenukk

**Comment by tokatoka** [comment]
I feel it is unrelated to OOM, I could once again reproduce this but the memory usage is very small.
I think OOM issue is completely fixed with the mapindexmetadata fix

**Comment by domenukk** [comment]
> there is `fatal runtime error: failed to initiate panic, error 5` dunno what is, we must solve the restart @domenukk

Not a very useful error output :/ Any ideas how to debug this?
