### ISSUE TITLE
Error when build `libfuzzer_libpng`

### ISSUE THREAD

**Issue by syheliel** [AFLplusplus/LibAFL#567]
I'm trying to run the example in `./fuzzer/libfuzzer_libpng`. In `README.md`, the first step is `cargo build --release`, but the main output is as follows:
```
error: failed to run custom build command for `libafl_cc v0.7.1 (/home/xxx/LibAFL/libafl_cc)`

Caused by:
  process didn't exit successfully: `/home/xxx/LibAFL/fuzzers/libfuzzer_libpng/target/debug/build/libafl_cc-79f99d7fa3c3fe18/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_CONFIG
  cargo:rerun-if-env-changed=LIBAFL_EDGES_MAP_SIZE
  cargo:rerun-if-env-changed=LIBAFL_ACCOUNTING_MAP_SIZE
  cargo:rerun-if-changed=src/common-llvm.h
  cargo:rerun-if-changed=src/cmplog-routines-pass.cc
  cargo:rerun-if-changed=src/afl-coverage-pass.cc
  cargo:rerun-if-changed=src/autotokens-pass.cc
  cargo:rerun-if-changed=src/coverage-accounting-pass.cc

  --- stderr
  thread 'main' panicked at 'Failed to compile cmplog-routines-pass.cc: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/xxx/LibAFL/libafl_cc/build.rs:191:14
  stack backtrace:
     0:     0x5629be295d4c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5629be295d4c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5629be295d4c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x5629be295d4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x5629be2b86ec - core::fmt::write::h753c7571fa063ecb
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
     5:     0x5629be2906c3 - std::io::Write::write_fmt::h2815c0519c99ba09
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
     6:     0x5629be298422 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x5629be298422 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x5629be298422 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
     9:     0x5629be298005 - std::panicking::default_hook::hda898f8d3ad1a5ae
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
    10:     0x5629be298a73 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
    11:     0x5629be298790 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
    12:     0x5629be2961f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
    13:     0x5629be2984c9 - rust_begin_unwind
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
    14:     0x5629be1fb9c1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
    15:     0x5629be1fba53 - core::result::unwrap_failed::ha0327e3803285d6e
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
    16:     0x5629be202f0f - core::result::Result<T,E>::expect::hf73e499b34f343c0
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:975:23
    17:     0x5629be1fe189 - build_script_build::main::h379700033abc222e
                                 at /home/xxx/LibAFL/libafl_cc/build.rs:183:17
    18:     0x5629be20383b - core::ops::function::FnOnce::call_once::h540fa15afdf6da3e
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
    19:     0x5629be201ebe - std::sys_common::backtrace::__rust_begin_short_backtrace::h10e466d56804fd51
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
    20:     0x5629be201e91 - std::rt::lang_start::{{closure}}::h9a093aa09cc3d788
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:145:18
    21:     0x5629be295400 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
    22:     0x5629be295400 - std::panicking::try::do_call::h1e21ba261ba489ec
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
    23:     0x5629be295400 - std::panicking::try::h6afd48af8b6c96ac
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
    24:     0x5629be295400 - std::panic::catch_unwind::h85dd95e0bab7fb60
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
    25:     0x5629be295400 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
    26:     0x5629be295400 - std::panicking::try::do_call::h6b0ad65979f3077a
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
    27:     0x5629be295400 - std::panicking::try::h010108d314169ac6
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
    28:     0x5629be295400 - std::panic::catch_unwind::hff397f912b1535c2
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
    29:     0x5629be295400 - std::rt::lang_start_internal::h52e73755f77c7dd9
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
    30:     0x5629be201e60 - std::rt::lang_start::h5f56c50cd7a64d37
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:144:17
    31:     0x5629be1fee9c - main
    32:     0x7fa98e7a1c87 - __libc_start_main
                                 at /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:310
    33:     0x5629be1fc0da - _start
    34:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Since `rust with gdb -- build --release` is unavaliable, I'm quite confused with the problem. I'd like to provide more information if it helps.

**Comment by domenukk** [comment]
Which version of llvm do you have installed? Maybe that could be the issue here?

**Comment by tokatoka** [comment]
Do you have cmplog-routines-pass.cc in libafl_cc?
I can't reproduce it

**Comment by syheliel** [comment]
> Which version of llvm do you have installed? Maybe that could be the issue here?

That hits my problem! I find that there are multiple versions of llvm and clang. Removing them all, installing `lllvm-12,clang-12` and linking `llvm-config` solve the problem.
