### ISSUE TITLE
thread 'main' panicked at 'Error in the fuzzing loop: Empty("No entries in corpus", ErrorBacktrace)', s rc/main.rs:167:10

### ISSUE THREAD

**Issue by docfate111** [AFLplusplus/LibAFL#928]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch
Yes
**Describe the bug**
thread 'main' panicked at 'Error in the fuzzing loop: Empty("No entries in corpus", ErrorBacktrace)', s
src/main.rs:167:10
Crashed with SIGABRT
Double Crash
**To Reproduce**
1. git clone https://github.com/docfate111/lklfuzzergrimore.git
2. cd lklfuzzergrimore
3. adjust the paths of LibAFL in Cargo.toml and src/main.rs
4. cargo run
(enter password for sudo to make the btrfs filesystem image)
**Expected behavior**
Some output about the fuzzer running should happen

**Screen output/Screenshots**
```
Loading file "/home/t/Fuzzing/lklfuzzergrimore/corpus/serialized86O0pDP7IuyH" ...                      
Loading file "/home/t/Fuzzing/lklfuzzergrimore/corpus/serializedK8340VD2ANzJ" ...                      
thread 'main' panicked at 'Error in the fuzzing loop: Empty("No entries in corpus", ErrorBacktrace)', s
rc/main.rs:167:10                                                                                      
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                          
Crashed with SIGABRT                                                                                   
Double crash

We crashed at addr 0x3e800017070, but are not in the target... Bug in the fuzzer? Exiting.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CRASH ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Received signal SIGABRT at 0x007f0ab4c8c64c, fault address: 0x00000000000000
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ REGISTERS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r8 : 0x00000000000000, r9 : 0x00000000000002, r10: 0x00000000000008, r11: 0x00000000000246, 
r12: 0x00000000000006, r13: 0x0055af119a1198, r14: 0x0055af119bbfe8, r15: 0x007fff467d8250, 
rdi: 0x00000000017070, rsi: 0x00000000017070, rbp: 0x007f0ab4c03080, rbx: 0x00000000017070, 
rdx: 0x00000000000006, rax: 0x00000000000000, rcx: 0x007f0ab4c8c64c, rsp: 0x007fff467d7fd0, 
rip: 0x007f0ab4c8c64c, efl: 0x00000000000246, 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   0: libafl::bolts::minibsod::generate_minibsod
             at /home/t/Fuzzing/LibAFL-0.8.2/libafl/src/bolts/minibsod.rs:438:30

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ MAPS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
55af11576000-55af115ec000 r--p 00000000 103:05 1342486                   /home/t/Fuzzing/lklfuzzergrimo
re/target/debug/lkl_fuzzer_grimoire
55af115ec000-55af11928000 r-xp 00076000 103:05 1342486                   /home/t/Fuzzing/lklfuzzergrimo
re/target/debug/lkl_fuzzer_grimoire
55af11928000-55af1199f000 r--p 003b2000 103:05 1342486                   /home/t/Fuzzing/lklfuzzergrimo
re/target/debug/lkl_fuzzer_grimoire
55af1199f000-55af119d5000 r--p 00428000 103:05 1342486                   /home/t/Fuzzing/lklfuzzergrimo
re/target/debug/lkl_fuzzer_grimoire
55af119d5000-55af119d6000 rw-p 0045e000 103:05 1342486                   /home/t/Fuzzing/lklfuzzergrimo
re/target/debug/lkl_fuzzer_grimoire
55af12c8b000-55af133ed000 rw-p 00000000 00:00 0                          [heap]
7f0ab0afc000-7f0ab0b89000 rw-p 00000000 00:00 0 
7f0ab0b89000-7f0ab0c8a000 rw-p 00000000 00:00 0 
7f0ab0d0b000-7f0ab0dcc000 rw-p 00000000 00:00 0 
7f0ab0e5e000-7f0ab4401000 r--p 00000000 103:05 1342486                   /home/t/Fuzzing/lklfuzzergrimo
re/target/debug/lkl_fuzzer_grimoire
7f0ab4401000-7f0ab4c04000 rw-p 00000000 00:00 0 
7f0ab4c04000-7f0ab4c26000 r--p 00000000 103:05 2893495                   /usr/lib/libc.so.6
7f0ab4c26000-7f0ab4d81000 r-xp 00022000 103:05 2893495                   /usr/lib/libc.so.6
7f0ab4d81000-7f0ab4dd8000 r--p 0017d000 103:05 2893495                   /usr/lib/libc.so.6
7f0ab4dd8000-7f0ab4ddc000 r--p 001d4000 103:05 2893495                   /usr/lib/libc.so.6
7f0ab4ddc000-7f0ab4dde000 rw-p 001d8000 103:05 2893495                   /usr/lib/libc.so.6
7f0ab4dde000-7f0ab4deb000 rw-p 00000000 00:00 0 
7f0ab4deb000-7f0ab4df9000 r--p 00000000 103:05 2893505                   /usr/lib/libm.so.6
7f0ab4df9000-7f0ab4e73000 r-xp 0000e000 103:05 2893505                   /usr/lib/libm.so.6
7f0ab4e73000-7f0ab4ed1000 r--p 00088000 103:05 2893505                   /usr/lib/libm.so.6
7f0ab4ed1000-7f0ab4ed2000 r--p 000e5000 103:05 2893505                   /usr/lib/libm.so.6
7f0ab4ed2000-7f0ab4ed3000 rw-p 000e6000 103:05 2893505                   /usr/lib/libm.so.6
7f0ab4ed3000-7f0ab4ed6000 r--p 00000000 103:05 2888269                   /usr/lib/libgcc_s.so.1
7f0ab4ed6000-7f0ab4eed000 r-xp 00003000 103:05 2888269                   /usr/lib/libgcc_s.so.1
7f0ab4eed000-7f0ab4ef1000 r--p 0001a000 103:05 2888269                   /usr/lib/libgcc_s.so.1
7f0ab4ef1000-7f0ab4ef2000 r--p 0001d000 103:05 2888269                   /usr/lib/libgcc_s.so.1
7f0ab4ef2000-7f0ab4ef3000 rw-p 0001e000 103:05 2888269                   /usr/lib/libgcc_s.so.1
7f0ab4f0a000-7f0ab4f0b000 ---p 00000000 00:00 0 
7f0ab4f0b000-7f0ab4f0f000 rw-p 00000000 00:00 0 
```

**Additional context**
I am linking with a library that runs the Linux kernel

**Comment by domenukk** [comment]
Have you tried to obvious and given it some initial corpus entries? Either read them from a folder or generate them

**Comment by tokatoka** [comment]
Your coverage map is `SIGNALS` but how does the harness write its coverage into this map?
https://github.com/docfate111/lklfuzzergrimore/blob/main/src/main.rs#L30

**Comment by docfate111** [comment]
> Have you tried to obvious and given it some initial corpus entries? Either read them from a folder or generate them

Yes. https://github.com/docfate111/lklfuzzergrimore/tree/main/corpus

**Comment by docfate111** [comment]
> Your coverage map is `SIGNALS` but how does the harness write its coverage into this map? https://github.com/docfate111/lklfuzzergrimore/blob/main/src/main.rs#L30
> 
> I guess, the problem is your fuzzer does not have any instrumentation You use
> 
> ```
>     let observer =
>         unsafe { StdMapObserver::new_from_ptr("signals", SIGNALS.as_mut_ptr(), SIGNALS.len()) };
> ```
> 
> for collecting the coverage, but SIGNALS is not what your harness writes its coverage into. So nothing is stored as the new corpus entry,

How do I collect coverage? I had a C library compiled with afl-gcc and is called by a Rust function.

**Comment by tokatoka** [comment]
> How do I collect coverage? I had a C library compiled with afl-gcc and is called by a Rust function.

If you use afl-cc from afl++ you can create a shmem and write that shmem id into `__AFL_SHM_ID` then the instrumented binary will write its coverage into this shmem.

Please see what this fuzzbench_forkserver is doing here https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/fuzzbench_forkserver/src/main.rs#L242

but your target is kinda special and things are more complex so maybe just compiling the harness with afl-cc does not work
